### ISSUE TITLE
what does this line mean in README?

### ISSUE THREAD

**Issue by illtellyoulater** [crowsonkb/v-diffusion-pytorch#16]
> A weight of 1 will sample images that match the prompt roughly as well as images usually match prompts like that in the training set. 

I can't wrap my head around this sentence. Could you please explain it with different wording? Thanks!

**Comment by crowsonkb** [comment]
One recurring problem we have with text to image models is that our paired image/text datasets just aren't as good as we would like. The images and captions rarely match very well. So we use this "classifier-free guidance" trick to sample conditional on stronger image/caption matching than was typical in the training set. If you use 1 the image will tend to match the caption about as well as images matched captions in the training set.

**Comment by illtellyoulater** [comment]
many thanks!
